# Generated by go2rpm 1.9.0
# Tests require credentials
%bcond_with check
%global debug_package %{nil}

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns
Version:                1.1.0
%global tag             sdk/resourcemanager/dns/armdns/v1.1.0
%global distprefix      %{nil}

%gometa -f

%global common_description %{expand:
Azure SDK for Go - DNS module.}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md SUPPORT.md\\\
                        SECURITY.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Azure SDK for Go - resourcemanager/dns/armdns library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

# move building library to the root to match goipath
mv sdk/resourcemanager/dns/armdns/* .
rm -rf .github documentation eng profile sdk

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
